import {describe,it,expect} from 'vitest';
import {BuySession,buyQuote,nextRoundMinimum,type Buyer} from '../src/game/buying';
import {newMatch,nextRound} from '../src/game/rules';
import {createWeapon} from '../src/game/weapons';
import {emptyGrenades} from '../src/game/grenades';
function fixture(){const match=newMatch('CT'),player:Buyer={id:0,team:0,name:'YOU',alive:true,health:100,armor:0,helmet:false,kit:false,money:10000,kills:0,deaths:0,inventory:[createWeapon('usp'),createWeapon('knife')],grenades:emptyGrenades(),grenadePurchases:emptyGrenades()},session=new BuySession();session.beginRound(match,player,true);return{match,player,session};}
describe('buy menu transactions',()=>{
  it('quotes the same incremental helmet price that is charged, then refunds exact amounts',()=>{const{match,player:p,session:s}=fixture();expect(s.buy(match,p,'armor',true)).toBe(true);expect(buyQuote(p,'CT','helmet').price).toBe(350);expect(s.buy(match,p,'helmet',true)).toBe(true);expect(p.money).toBe(9000);expect(s.refundAll(match,p,true)).toBe(2);expect(p.money).toBe(10000);expect(p.armor).toBe(0);expect(p.helmet).toBe(false);expect(s.refundAll(match,p,true)).toBe(0);});
  it('cannot buy outside the zone, while live, on the wrong side or without funds',()=>{const{match,player:p,session:s}=fixture();expect(s.buy(match,p,'ak47',true)).toBe(false);expect(s.buy(match,p,'awp',false)).toBe(false);match.phase='live';expect(s.buy(match,p,'awp',true)).toBe(false);match.phase='freeze';p.money=100;expect(s.buy(match,p,'deagle',true)).toBe(false);expect(p.money).toBe(100);});
  it('restores the replaced carried weapon without selling it, and cannot refund twice',()=>{const{match,player:p,session:s}=fixture(),carried=p.inventory[0];expect(s.buy(match,p,'deagle',true)).toBe(true);expect(s.refund(match,p,'usp',true)).toBe(false);expect(s.refund(match,p,'deagle',true)).toBe(true);expect(p.inventory).toContain(carried);expect(p.money).toBe(10000);expect(s.refund(match,p,'deagle',true)).toBe(false);});
  it('rejects refunds for fired, dropped or substituted weapons',()=>{const{match,player:p,session:s}=fixture();s.buy(match,p,'m4a1',true);const gun=p.inventory.find(w=>w.id==='m4a1')!;gun.ammo--;expect(s.refund(match,p,'m4a1',true)).toBe(false);gun.ammo++;p.inventory=p.inventory.filter(w=>w!==gun);p.inventory.push({...gun});expect(s.refund(match,p,'m4a1',true)).toBe(false);});
  it('unwinds consecutive replacements without creating money or duplicate weapons',()=>{const{match,player:p,session:s}=fixture();s.buy(match,p,'m4a1',true);s.buy(match,p,'awp',true);expect(s.refundAll(match,p,true)).toBe(2);expect(p.money).toBe(10000);expect(p.inventory.map(w=>w.id).sort()).toEqual(['knife','usp']);});
  it('returns grenade purchase quota, preserving carried grenades and rejecting consumed ones',()=>{const{match,player:p,session:s}=fixture();p.grenades.flash=p.grenadePurchases.flash=1;s.buy(match,p,'flash',true);expect(p.grenades.flash).toBe(2);expect(s.refund(match,p,'flash',true)).toBe(true);expect(p.grenades.flash).toBe(1);expect(p.grenadePurchases.flash).toBe(1);expect(s.refund(match,p,'flash',true)).toBe(false);s.buy(match,p,'he',true);p.grenades.he=0;expect(s.refund(match,p,'he',true)).toBe(false);});
  it('refunds kits independently from armor without overwriting other equipment',()=>{const{match,player:p,session:s}=fixture();s.buy(match,p,'kit',true);s.buy(match,p,'helmet',true);expect(s.refund(match,p,'kit',true)).toBe(true);expect(p.kit).toBe(false);expect(p.armor).toBe(100);expect(p.helmet).toBe(true);expect(s.refund(match,p,'helmet',true)).toBe(true);expect(p.money).toBe(10000);});
  it('expires receipts at round boundaries and retains a rebuy plan',()=>{const{match,player:p,session:s}=fixture();s.buy(match,p,'m4a1',true);s.buy(match,p,'smoke',true);nextRound(match);s.beginRound(match,p);expect(s.refund(match,p,'m4a1',true)).toBe(false);expect(s.canRebuy).toBe(true);p.inventory=[createWeapon('usp'),createWeapon('knife')];p.grenades=emptyGrenades();p.grenadePurchases=emptyGrenades();p.money=10000;expect(s.rebuy(match,p,true)).toBe(2);expect(p.inventory.some(w=>w.id==='m4a1')).toBe(true);expect(p.grenades.smoke).toBe(1);expect(s.rebuy(match,p,true)).toBe(0);});
  it('keeps automatic buys within funds and displays the actual loss compensation floor',()=>{const{match,player:p,session:s}=fixture();p.money=800;s.autoBuy(match,p,true);expect(p.money).toBe(150);expect(p.armor).toBe(100);expect(nextRoundMinimum(match,p)).toBe(1550);match.lossStreak[0]=4;expect(nextRoundMinimum(match,p)).toBe(3550);p.money=15900;expect(nextRoundMinimum(match,p)).toBe(16000);});
  it('buys a donation without replacing or refunding the donor’s weapon',()=>{const{match,player:p,session:s}=fixture();const carried=p.inventory[0];expect(buyQuote(p,'CT','usp').enabled).toBe(false);expect(buyQuote(p,'CT','usp',true).enabled).toBe(true);const gift=s.donate(match,p,'usp',true);expect(gift?.id).toBe('usp');expect(p.inventory).toContain(carried);expect(p.inventory).not.toContain(gift);expect(p.money).toBe(9800);expect(s.refund(match,p,'usp',true)).toBe(false);expect(s.donate(match,p,'ak47',true)).toBeNull();});
  it('retains the previous purchase plan after death and consumed grenades',()=>{const{match,player:p,session:s}=fixture();s.buy(match,p,'m4a1',true);s.buy(match,p,'smoke',true);p.inventory=[createWeapon('knife')];p.grenades=emptyGrenades();p.alive=false;nextRound(match);s.beginRound(match,p);p.alive=true;p.inventory=[createWeapon('usp'),createWeapon('knife')];p.grenadePurchases=emptyGrenades();p.money=10000;expect(s.rebuy(match,p,true)).toBe(2);expect(p.inventory.some(w=>w.id==='m4a1')).toBe(true);expect(p.grenades.smoke).toBe(1);});
});
