import{beforeAll,describe,it,expect}from'vitest';import RAPIER from'@dimforge/rapier3d-compat';import{Group,Quaternion,Vector3}from'three';import{LootPhysics}from'../src/game/loot-physics';import{autoWeaponPickup,pickupReach,deathWeapon}from'../src/game/pickups';import{createWeapon}from'../src/game/weapons';import type{Combatant}from'../src/game/types';
beforeAll(async()=>{await RAPIER.init();});
describe('dropped equipment physics and ownership',()=>{
 it('falls, stays above the floor, sleeps, and releases its rigid body after pickup',()=>{
  const world=new RAPIER.World({x:0,y:-20,z:0});world.createCollider(RAPIER.ColliderDesc.cuboid(20,.1,20).setTranslation(0,-.1,0));const mesh=new Group();mesh.userData.halfExtents={x:.025,y:.1,z:.4};const loot=new LootPhysics(world),item=loot.add(mesh,{x:0,y:1.4,z:0},new Quaternion(),{x:1,y:1,z:-2});
  for(let i=0;i<600;i++){world.step();loot.update();}expect(item.position.y).toBeGreaterThan(.005);expect(item.position.y).toBeLessThan(.42);expect(Math.abs(item.position.z)).toBeGreaterThan(.2);expect(item.body.isSleeping()).toBe(true);const updates=loot.stats.updates;for(let i=0;i<60;i++){world.step();loot.update();}expect(loot.stats.updates).toBe(updates);loot.remove(item);expect(world.bodies.len()).toBe(0);world.free();
 });
 it('does not tunnel through a thin wall when tossed at high speed',()=>{const world=new RAPIER.World({x:0,y:0,z:0});world.createCollider(RAPIER.ColliderDesc.cuboid(.025,5,5).setTranslation(1,0,0));const mesh=new Group();mesh.userData.halfExtents={x:.08,y:.05,z:.3};const loot=new LootPhysics(world),item=loot.add(mesh,{x:0,y:1,z:0},new Quaternion(),{x:25,y:0,z:0});for(let i=0;i<60;i++){world.step();loot.update();expect(item.position.x).toBeLessThan(1);}loot.clear();expect(world.bodies.len()).toBe(0);world.free();});
 it('automatically fills only empty weapon slots and preserves the current gun',()=>{const p={alive:true,inventory:[createWeapon('usp'),createWeapon('knife')]}as Combatant;expect(autoWeaponPickup(p,createWeapon('ak47'))).toBe(true);expect(autoWeaponPickup(p,createWeapon('deagle'))).toBe(false);p.inventory.push(createWeapon('ak47'));expect(autoWeaponPickup(p,createWeapon('m4a1'))).toBe(false);expect(deathWeapon(p)?.id).toBe('ak47');p.alive=false;expect(autoWeaponPickup(p,createWeapon('awp'))).toBe(false);});
 it('separates touching range from deliberate reach and rejects another floor',()=>{const p=new Vector3();expect(pickupReach(p,{x:.8,y:.2,z:0})).toBe(true);expect(pickupReach(p,{x:1.7,y:.1,z:0})).toBe(false);expect(pickupReach(p,{x:1.7,y:.1,z:0},true)).toBe(true);expect(pickupReach(p,{x:0,y:2,z:0},true)).toBe(false);});
});
